import type { NextPage } from 'next'
import Head from 'next/head'
import item from '../components/item'
import useListItems from '../api/useListItems'

const Fetch: NextPage = () => {
  const { data, error } = useListItems('https://fetch-hiring.s3.amazonaws.com/hiring.json')

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <div>
      <Head>
        <title>Fetch Exercise App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Data</h1>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>List ID</th>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            {Object.keys(data).map((listId) => {
              return data[listId].map(item)
            })}
          </tbody>
        </table>
      </main>
    </div>
  )
}

export default Fetch
